title: HDAdvisors
description: Website for Richmond, Virginia based consulting firm for affordable housing.
url: https://www.hdadvisors.net
author: HDAdvisors

# SEO specific settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Social media presence (if applicable)
social:
  name: HDAdvisors
  links:
    - https://linkedin.com/company/hdadvisors