project:
  type: website
  output-dir: docs
  resources:
    - images/

website:
  title: "HDAdvisors"
  description: "Affordable Housing Consulting"
  site-url: https://hdadvisors.net
  sitemap: true
  favicon: images/favicon.png
  page-navigation: false
  
  # Footer configuration
  page-footer: 
    background: "#F6F5F3"
    left: |
      203 N. Robinson St., Richmond VA, 23220<br>
      [admin@hdadvisors.net](mailto:admin@hdadvisors.net)
    right: © 2024  &middot; Made with [![](https://www.r-project.org/Rlogo.png){fig-alt="R" width=30px}](https://www.r-project.org/) and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=30px}](https://quarto.org/) 

  # Navbar configuration
  navbar:
    search: true
    title: false
    logo: images/hda-logo-rgb.png
    background: white
    foreground: primary
    collapse-below: lg
    padding: 0px     # Reduce padding around navbar elements
    left:
      - text: Home
        href: index.qmd
      - text: About
        menu:
          - href: about.qmd
          - href: staff.qmd
      - text: What We Do
        menu:
          - text: Services
            href: services.qmd
      - text: Blog
        href: blog/index.qmd
    right:
      - icon: rss
        href: blog/index.xml
      - icon: envelope
        href: "mailto:admin@hdadvisors.net"
      - icon: linkedin
        href: https://www.linkedin.com/company/hdadvisors
      - icon: github
        href: https://github.com/hdadvisors/
# RSS feed configuration
feed:
  title: "Housing Starts"
  description: "Insights on affordable housing, policy research, and data visualization"
  categories:
    - affordable housing
    - policy research
    - data visualization
    - Richmond
    - Virginia
  items: 20
  language: en-US
  image: "images/hda-logo-rgb.png"
  copyright: "© 2025 HDAdvisors"

format:
  html:
    theme: 
      - yeti
      - styles/custom.scss
    css: styles/additional.css  # For any additional CSS tweaks without recompiling SCSS
    toc: false                  # Remove default table of contents
    page-layout: full           # Use full width for all pages by default
    margin-top: 0px             # Remove top margin throughout the site
    margin-bottom: 0px          # Remove bottom margin
    smooth-scroll: true         # Enable smooth scrolling
    code-link: true             # Clickable code links
    template: _template.html